import styled from "styled-components";
/**
 * `<Group36>` ('Group 36')
 * - [Open in Figma](https://figma.com/file/ccmRe7vzcfeTsD78jd0hHR?node-id=149:2538)
 * - [Open in Grida](https://code.grida.co/files/ccmRe7vzcfeTsD78jd0hHR?node=149:2538)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Group36/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/149:2538)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://ccmRe7vzcfeTsD78jd0hHR/149:2538 -->
 */
export default function SignupPopup() {
  return (
    <RootWrapperGroup36>
      <Rectangle24 />
    </RootWrapperGroup36>
  );
}

const RootWrapperGroup36 = styled.div`
	position: relative;
	box-shadow: -4px 4px 29px  rgba(0, 0, 0, 0.25);
`;

const Rectangle24 = styled.div`
	width: 622px;
	height: 786px;
	box-shadow: 5px 6px 16px 2px rgba(0, 0, 0, 0.25);
	background-color: white;
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;