import Jumbotron from 'components/Jumbotron'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import ResourceCard from 'components/ResourceCard'
import { useQuery } from '@apollo/client'
import { GET_RESOURCES } from 'graphql/queries'

export default function Home() {
  const { loading, error, data } = useQuery(GET_RESOURCES)
  console.log(loading)
  console.log(error)
  console.log(data)
  return (
    <div>
      <Head>
        <title>EdisHub - your source for tech resources </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />

      {/* <ResourceCard /> */}
    </div>
  )
}
