import Jumbotron from 'components/Jumbotron'
import Head from 'next/head'
import styled from 'components-styled'

import Button from 'react-bootstrap/Button'

import EdisMantra from 'components/EdisMantra'
import ResourceCard from 'components/ResourceCard'
import { useQuery } from '@apollo/client'
import { GET_RESOURCES } from 'queries/queries'
import FeaturedSection from 'components/FeaturedSection'
import { Container } from 'react-bootstrap'

export default function Home() {
  const { loading, error, data } = useQuery(GET_RESOURCES)
  console.log(loading)
  console.log(error)
  console.log(data)
  return (
    <div>
      <Head>
        <title>EdisHub - your source for tech resources </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />
      <EdisMantra />
      
      <Container>
      <Button variant="outline-primary">Beginner</Button>{' '}
      <Button variant="outline-primary">Intermidiate</Button>{' '}
      <Button variant="outline-primary">Advanced</Button>{' '}
      </Container>

      <FeaturedSection />
    </div>
  )
}
