import styled from "styled-components";
/**
 * `<ExploreResourcesPage>` ('EXPLORE RESOURCES PAGE')
 * - [Open in Figma](https://figma.com/file/ccmRe7vzcfeTsD78jd0hHR?node-id=189:2384)
 * - [Open in Grida](https://code.grida.co/files/ccmRe7vzcfeTsD78jd0hHR?node=189:2384)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <ExploreResourcesPage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/189:2384)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://ccmRe7vzcfeTsD78jd0hHR/189:2384 -->
 */

import Link from "next/link" ;

export default function ExploreResourcesPage() {
  return (
    <RootWrapperExploreResourcesPage>
      <Rectangle26 />
      <Rectangle27 />
      <LogIn>Log In</LogIn>
      <SignUp>Sign Up</SignUp>
      <EdisHub>{"{EdisHub}"}</EdisHub>
      <Group14>
        <Categories>Categories</Categories>
      </Group14>
      <Group27>
        <Rectangle16 />
        <SearchForAnything>Search for Anything</SearchForAnything>
      </Group27>
      <Rectangle15 />
      <ExploreDevelopmentResources>
        Explore Development
        <br />
        Resources
      </ExploreDevelopmentResources>
      <WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds>
        Whether you’re a full-time student, bootcamp graduate, or working professional, we’ve got
        resources curated for your needs.
      </WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds>
      <SelectYourLevelOfLearning>Select your level of learning</SelectYourLevelOfLearning>
      <SelectTheAppropriateTopicS>Select the appropriate topic(s)</SelectTheAppropriateTopicS>
      <LearnAtYourOwnPace>Learn at your own pace</LearnAtYourOwnPace>
      <Learning1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a6857f51-ba1e-4a83-ac40-0e506b83c963"
        alt="image of Learning1"
      />
      <Settings11
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ec9275e0-8b7b-46dc-ac1d-588a602e3f40"
        alt="image of Settings11"
      />
      <TrendingTopic1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/68ffe05f-77df-46c2-adc7-b41ecbde05d7"
        alt="image of TrendingTopic1"
        />
      <Group39>
        <Rectangle24 />
      </Group39>
      <Group43>
        <Rectangle24_0001 />
      </Group43>
      <Group40>
        <Rectangle24_0001 />
      </Group40>
      <Group44>
        <Rectangle24_0001 />
      </Group44>
      <Group41>
        <Rectangle24_0001 />
      </Group41>
      <Group45>
        <Rectangle24_0001 />
      </Group45>
      <Group42>
        <Rectangle24_0001 />
      </Group42>
      <Group46>
        <Rectangle24_0001 />
      </Group46>
      <FundementalsWebDevelopment>
        Fundamentals
        <br />
        Web Development
      </FundementalsWebDevelopment>
      <BlahBlah>Blah blah</BlahBlah>
      <BlahBlah_0001>Blah blah</BlahBlah_0001>
      <BlahBlah_0002>Blah blah</BlahBlah_0002>
      <BlahBlah_0003>Blah blah</BlahBlah_0003>
      <BlahBlah_0004>Blah blah</BlahBlah_0004>
      <BlahBlah_0005>Blah blah</BlahBlah_0005>
      <BlahBlah_0006>Blah blah</BlahBlah_0006>
      <Rectangle44 />
      <Continue> <Link href="/ResourcePicks">
        <a style ={{
            color:"white",
            textDecoration: "none",
        
          }}>
            Continue
         </a>
         </Link>
      </Continue>
      <OrViewAllDevelopmentResources>
        or view all development resources
      </OrViewAllDevelopmentResources>
      <SelectYourResourceCategories>Select Your Resource Categories</SelectYourResourceCategories>
      <MaySelectMultiple>(may select multiple)</MaySelectMultiple>
      <Vector xmlns="http://www.w3.org/2000/svg">
        <path
          fill="black"
          d="M1.5275 0L6.5 5.11123L11.4725 0L13 1.57354L6.5 8.26947L0 1.57354L1.5275 0Z"
        />
      </Vector>
      <Vector_0001 xmlns="http://www.w3.org/2000/svg">
        <path
          fill="rgb(167, 167, 167)"
          d="M13.5792 12.3522L12.721 12.3522L12.4168 12.049C13.4814 10.7689 14.1224 9.10694 14.1224 7.29903C14.1224 3.26772 10.9611 0 7.06118 0C3.16124 0 0 3.26772 0 7.29903C0 11.3303 3.16124 14.5981 7.06118 14.5981C8.81018 14.5981 10.418 13.9355 11.6564 12.8351L11.9497 13.1495L11.9497 14.0366L17.3814 19.64L19 17.9668L13.5792 12.3522L13.5792 12.3522ZM7.06118 12.3522C4.3562 12.3522 2.17267 10.0951 2.17267 7.29903C2.17267 4.50294 4.3562 2.24585 7.06118 2.24585C9.76615 2.24585 11.9497 4.50294 11.9497 7.29903C11.9497 10.0951 9.76615 12.3522 7.06118 12.3522Z"
        />
      </Vector_0001>
    </RootWrapperExploreResourcesPage>
  );
}

const RootWrapperExploreResourcesPage = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Rectangle26 = styled.div`
	width: 115px;
	height: 48px;
	background-color: white;
	border: solid 1px rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 1038px;
	top: 42px;
`;

const Rectangle27 = styled.div`
	width: 115px;
	height: 48px;
	background-color: rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 1178px;
	top: 42px;
`;

const LogIn = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 93px;
	min-height: 37px;
	position: absolute;
	left: 1050px;
	top: 48px;
	height: 37px;
`;

const SignUp = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 95px;
	min-height: 37px;
	position: absolute;
	left: 1190px;
	top: 48px;
	height: 37px;
`;

const EdisHub = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: "Nova Oval", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 151px;
	min-height: 129px;
	position: absolute;
	left: 219px;
	top: 0px;
	height: 129px;
`;

const Group14 = styled.div`
	width: 102px;
	height: 36px;
	position: absolute;
	left: 392px;
	top: 46px;
`;

const Categories = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 102px;
	min-height: 36px;
	position: absolute;
	left: 0px;
	top: 0px;
	height: 36px;
`;

const Group27 = styled.div`
	width: 472px;
	height: 48px;
	position: absolute;
	left: 530px;
	top: 42px;
`;

const Rectangle16 = styled.div`
	width: 472px;
	height: 48px;
	background-color: white;
	border: solid 1px black;
	border-radius: 50px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const SearchForAnything = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 273px;
	min-height: 38px;
	position: absolute;
	left: 41px;
	top: 5px;
	height: 38px;
`;

const Rectangle15 = styled.div`
	width: 1512px;
	height: 302px;
	background-color: rgba(56, 95, 185, 0.17);
	position: absolute;
	left: 0px;
	top: 128px;
`;

const ExploreDevelopmentResources = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 48px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 745px;
	min-height: 148px;
	position: absolute;
	left: 213px;
	top: 160px;
	height: 148px;
`;

const WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 431px;
	min-height: 36px;
	position: absolute;
	left: 213px;
	top: 323px;
	height: 36px;
`;

const SelectYourLevelOfLearning = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 141px;
	min-height: 36px;
	position: absolute;
	left: 791px;
	top: 323px;
	height: 36px;
`;

const SelectTheAppropriateTopicS = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 173px;
	min-height: 36px;
	position: absolute;
	left: 965px;
	top: 323px;
	height: 36px;
`;

const LearnAtYourOwnPace = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 127px;
	min-height: 36px;
	position: absolute;
	left: 1171px;
	top: 323px;
	height: 36px;
`;

const Learning1 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 1178px;
	top: 190px;
`;

const Settings11 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 812px;
	top: 190px;
`;

const TrendingTopic1 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 1002px;
	top: 190px;
`;

const Group39 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 262px;
	top: 644px;
`;

const Rectangle24 = styled.div`
	width: 224px;
	height: 117px;
	box-shadow: 0px 2px 9px -2px rgb(56, 95, 185);
	background-color: rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group43 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 262px;
	top: 792px;
`;

const Rectangle24_0001 = styled.div`
	width: 224px;
	height: 117px;
	box-shadow: 0px 2px 9px -2px rgb(56, 95, 185);
	background-color: white;
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group40 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 517px;
	top: 644px;
`;

const Group44 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 517px;
	top: 792px;
`;

const Group41 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 775px;
	top: 644px;
`;

const Group45 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 775px;
	top: 792px;
`;

const Group42 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 1029px;
	top: 644px;
`;

const Group46 = styled.div`
	width: 224px;
	height: 117px;
	position: absolute;
	left: 1029px;
	top: 792px;
`;

const FundementalsWebDevelopment = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 235px;
	min-height: 49px;
	position: absolute;
	left: 258px;
	top: 678px;
	height: 49px;
`;

const BlahBlah = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 235px;
	min-height: 49px;
	position: absolute;
	left: 513px;
	top: 678px;
	height: 49px;
`;

const BlahBlah_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 235px;
	min-height: 49px;
	position: absolute;
	left: 513px;
	top: 826px;
	height: 49px;
`;

const BlahBlah_0002 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 235px;
	min-height: 49px;
	position: absolute;
	left: 258px;
	top: 826px;
	height: 49px;
`;

const BlahBlah_0003 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 235px;
	min-height: 49px;
	position: absolute;
	left: 771px;
	top: 678px;
	height: 49px;
`;

const BlahBlah_0004 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 235px;
	min-height: 49px;
	position: absolute;
	left: 771px;
	top: 826px;
	height: 49px;
`;

const BlahBlah_0005 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 177px;
	min-height: 49px;
	position: absolute;
	left: 1053px;
	top: 678px;
	height: 49px;
`;

const BlahBlah_0006 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 177px;
	min-height: 49px;
	position: absolute;
	left: 1053px;
	top: 826px;
	height: 49px;
`;

const Rectangle44 = styled.div`
	width: 500px;
	height: 65px;
	background-color: rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 506px;
	top: 982px;
`;

const Continue = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: center;
	width: 270px;
	min-height: 36px;
	position: absolute;
	left: 621px;
	top: 997px;
	height: 36px;
`;

const OrViewAllDevelopmentResources = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 276px;
	min-height: 36px;
	position: absolute;
	left: 618px;
	top: 1059px;
	height: 36px;
`;

const SelectYourResourceCategories = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 553px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 520px;
	height: 60px;
`;

const MaySelectMultiple = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 274px;
	min-height: 36px;
	position: absolute;
	left: 139px;
	top: 572px;
	height: 36px;
`;

const Vector = styled.svg`
	width: 13px;
	height: 8px;
	position: absolute;
	left: 494px;
	top: 64px;
	right: 1005px;
	bottom: 1080px;
`;

const Vector_0001 = styled.svg`
	width: 19px;
	height: 20px;
	position: absolute;
	left: 547px;
	top: 59px;
	right: 946px;
	bottom: 1073px;
`;