import ResourceCard from "components/ResourceCard";
import styled from "styled-components";
/**
 * `<ExploreResourcesPage>` ('EXPLORE RESOURCES PAGE')
 * - [Open in Figma](https://figma.com/file/ccmRe7vzcfeTsD78jd0hHR?node-id=182:2089)
 * - [Open in Grida](https://code.grida.co/files/ccmRe7vzcfeTsD78jd0hHR?node=182:2089)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <ExploreResourcesPage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/182:2089)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://ccmRe7vzcfeTsD78jd0hHR/182:2089 -->
 */
export default function ExploreResourcesPage() {
  return (
    <RootWrapperExploreResourcesPage>
      <Rectangle26 />
      <Rectangle27 />
      <LogIn>Log In</LogIn>
      <SignUp>Sign Up</SignUp>
      <EdisHub>{"{EdisHub}"}</EdisHub>
      <Group14>
        <Categories>Categories</Categories>
      </Group14>
      <Group27>
        <Rectangle16 />
        <SearchForAnything>Search for Anything</SearchForAnything>
      </Group27>
      <Rectangle15 />
      <ExploreDevelopmentResources>
        Explore Development
        <br />
        Resources
      </ExploreDevelopmentResources>
      <WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds>
        Whether you’re a full-time student, bootcamp graduate, or working professional, we’ve got
        resources curated for your needs.
      </WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds>
      <SelectYourLevelOfLearning>Select your level of learning</SelectYourLevelOfLearning>
      <SelectTheAppropriateTopicS>Select the appropriate topic(s)</SelectTheAppropriateTopicS>
      <LearnAtYourOwnPace>Learn at your own pace</LearnAtYourOwnPace>
	  <Learning1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a6857f51-ba1e-4a83-ac40-0e506b83c963"
        alt="image of Learning1"
      />
      <Settings11
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ec9275e0-8b7b-46dc-ac1d-588a602e3f40"
        alt="image of Settings11"
      />
      <TrendingTopic1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/68ffe05f-77df-46c2-adc7-b41ecbde05d7"
        alt="image of TrendingTopic1"
      />
      <YourResourcePicks>Your Resource Picks</YourResourcePicks>
      <_10Results>(10 results)</_10Results>
      <Group18>
        <Rectangle24 />
      </Group18>
      <Group32>
        <Rectangle24 />
      </Group32>
      <Group28>
        <Rectangle24 />
      </Group28>
      <Group33>
        <Rectangle24 />
      </Group33>
      
  {/* <ResourceCard /> */}
	  <Rectangle7 src="/images/Rectangle7.png" width=""alt="image of Rectangle7" />
      <Rectangle29 src="/images/Rectangle7.png" width=""alt="image of Rectangle7" />
      <Rectangle28 src="/images/Rectangle7.png" width=""alt="image of Rectangle7" />
      <Rectangle30 src="/images/Rectangle7.png" width=""alt="image of Rectangle7" />
      <IntroductionToComputerScience>
        Introduction to
        <br />
        Computer Science
      </IntroductionToComputerScience>
      <IntroductionToComputerScience_0001>
        Introduction to
        <br />
        Computer Science
      </IntroductionToComputerScience_0001>
      <IntroductionToComputerScience_0002>
        Introduction to
        <br />
        Computer Science
      </IntroductionToComputerScience_0002>
      <IntroductionToComputerScience_0003>
        Introduction to
        <br />
        Computer Science
      </IntroductionToComputerScience_0003>
      <HarvardUniversityCourse60Minutes>
        Harvard University Course | 60 minutes
      </HarvardUniversityCourse60Minutes>
      <HarvardUniversityCourse60Minutes_0001>
        Harvard University Course | 60 minutes
      </HarvardUniversityCourse60Minutes_0001>
      <HarvardUniversityCourse60Minutes_0002>
        Harvard University Course | 60 minutes
      </HarvardUniversityCourse60Minutes_0002>
      <HarvardUniversityCourse60Minutes_0003>
        Harvard University Course | 60 minutes
      </HarvardUniversityCourse60Minutes_0003>
      <Group15>
        <Rectangle17 />
        <StaffPicked>Staff-Picked</StaffPicked>
      </Group15>
      <Group34>
        <Rectangle17 />
        <StaffPicked>Staff-Picked</StaffPicked>
      </Group34>
      <Group29>
        <Rectangle17 />
        <StaffPicked>Staff-Picked</StaffPicked>
      </Group29>
      <Group35>
        <Rectangle17 />
        <StaffPicked>Staff-Picked</StaffPicked>
      </Group35>
      <Group16>
        <Rectangle28_0001 />
        <Beginner>Beginner</Beginner>
      </Group16>
      <Group36>
        <Rectangle28_0001 />
        <Beginner>Beginner</Beginner>
      </Group36>
      <Group30>
        <Rectangle28_0001 />
        <Beginner>Beginner</Beginner>
      </Group30>
      <Group37>
        <Rectangle28_0001 />
        <Beginner>Beginner</Beginner>
      </Group37>
      <Group17>
        <Rectangle29_0001 />
        <Free>Free</Free>
      </Group17>
      <Group38>
        <Rectangle29_0001 />
        <Free>Free</Free>
      </Group38>
      <Group31>
        <Rectangle29_0001 />
        <Free>Free</Free>
      </Group31>
      <Group39>
        <Rectangle29_0001 />
        <Free>Free</Free>
      </Group39>
      <Bookmark>Bookmark</Bookmark>
      <Bookmark_0001>Bookmark</Bookmark_0001>
      <Bookmark_0002>Bookmark</Bookmark_0002>
      <Bookmark_0003>Bookmark</Bookmark_0003>
      <_15Comments>15 Comments</_15Comments>
      <_15Comments_0001>15 Comments</_15Comments_0001>
      <_15Comments_0002>15 Comments</_15Comments_0002>
      <_15Comments_0003>15 Comments</_15Comments_0003>
      <FaRegularCommentAlt>
        <Vector xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M11.375 0L1.625 0C0.728711 0 0 0.672656 0 1.5L0 8.25C0 9.07734 0.728711 9.75 1.625 9.75L4.0625 9.75L4.0625 11.7188C4.0625 11.8852 4.20977 12 4.36719 12C4.42812 12 4.4916 11.9836 4.54746 11.9438L7.71875 9.75L11.375 9.75C12.2713 9.75 13 9.07734 13 8.25L13 1.5C13 0.672656 12.2713 0 11.375 0ZM11.7812 8.25C11.7812 8.45625 11.5984 8.625 11.375 8.625L7.3125 8.625L6.9875 8.85L5.28125 10.0312L5.28125 8.625L1.625 8.625C1.40156 8.625 1.21875 8.45625 1.21875 8.25L1.21875 1.5C1.21875 1.29375 1.40156 1.125 1.625 1.125L11.375 1.125C11.5984 1.125 11.7812 1.29375 11.7812 1.5L11.7812 8.25Z"
          />
        </Vector>
      </FaRegularCommentAlt>
      <FaRegularCommentAlt_0001>
        <Vector xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M11.375 0L1.625 0C0.728711 0 0 0.672656 0 1.5L0 8.25C0 9.07734 0.728711 9.75 1.625 9.75L4.0625 9.75L4.0625 11.7188C4.0625 11.8852 4.20977 12 4.36719 12C4.42812 12 4.4916 11.9836 4.54746 11.9438L7.71875 9.75L11.375 9.75C12.2713 9.75 13 9.07734 13 8.25L13 1.5C13 0.672656 12.2713 0 11.375 0ZM11.7812 8.25C11.7812 8.45625 11.5984 8.625 11.375 8.625L7.3125 8.625L6.9875 8.85L5.28125 10.0312L5.28125 8.625L1.625 8.625C1.40156 8.625 1.21875 8.45625 1.21875 8.25L1.21875 1.5C1.21875 1.29375 1.40156 1.125 1.625 1.125L11.375 1.125C11.5984 1.125 11.7812 1.29375 11.7812 1.5L11.7812 8.25Z"
          />
        </Vector>
      </FaRegularCommentAlt_0001>
      <FaRegularCommentAlt_0002>
        <Vector xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M11.375 0L1.625 0C0.728711 0 0 0.672656 0 1.5L0 8.25C0 9.07734 0.728711 9.75 1.625 9.75L4.0625 9.75L4.0625 11.7188C4.0625 11.8852 4.20977 12 4.36719 12C4.42812 12 4.4916 11.9836 4.54746 11.9438L7.71875 9.75L11.375 9.75C12.2713 9.75 13 9.07734 13 8.25L13 1.5C13 0.672656 12.2713 0 11.375 0ZM11.7812 8.25C11.7812 8.45625 11.5984 8.625 11.375 8.625L7.3125 8.625L6.9875 8.85L5.28125 10.0312L5.28125 8.625L1.625 8.625C1.40156 8.625 1.21875 8.45625 1.21875 8.25L1.21875 1.5C1.21875 1.29375 1.40156 1.125 1.625 1.125L11.375 1.125C11.5984 1.125 11.7812 1.29375 11.7812 1.5L11.7812 8.25Z"
          />
        </Vector>
      </FaRegularCommentAlt_0002>
      <FaRegularCommentAlt_0003>
        <Vector xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M11.375 0L1.625 0C0.728711 0 0 0.672656 0 1.5L0 8.25C0 9.07734 0.728711 9.75 1.625 9.75L4.0625 9.75L4.0625 11.7188C4.0625 11.8852 4.20977 12 4.36719 12C4.42812 12 4.4916 11.9836 4.54746 11.9438L7.71875 9.75L11.375 9.75C12.2713 9.75 13 9.07734 13 8.25L13 1.5C13 0.672656 12.2713 0 11.375 0ZM11.7812 8.25C11.7812 8.45625 11.5984 8.625 11.375 8.625L7.3125 8.625L6.9875 8.85L5.28125 10.0312L5.28125 8.625L1.625 8.625C1.40156 8.625 1.21875 8.45625 1.21875 8.25L1.21875 1.5C1.21875 1.29375 1.40156 1.125 1.625 1.125L11.375 1.125C11.5984 1.125 11.7812 1.29375 11.7812 1.5L11.7812 8.25Z"
          />
        </Vector>
      </FaRegularCommentAlt_0003>
      <BiBookmark>
        <Vector_0004 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M0 1.5C-1.80411e-16 1.10218 0.171205 0.720644 0.475951 0.43934C0.780698 0.158035 1.19402 4.57967e-16 1.625 8.32667e-17L8.125 0C8.55598 2.08167e-16 8.9693 0.158035 9.27405 0.43934C9.57879 0.720644 9.75 1.10218 9.75 1.5L9.75 11.625C9.74996 11.6928 9.72999 11.7594 9.69222 11.8176C9.65445 11.8758 9.60028 11.9234 9.5355 11.9554C9.47072 11.9874 9.39774 12.0026 9.32434 11.9994C9.25094 11.9961 9.17986 11.9746 9.11869 11.937L4.875 9.82575L0.631312 11.937C0.570136 11.9746 0.499062 11.9961 0.425662 11.9994C0.352261 12.0026 0.279283 11.9874 0.2145 11.9554C0.149716 11.9234 0.0955533 11.8758 0.0577802 11.8176C0.020007 11.7594 3.79603e-05 11.6928 0 11.625L0 1.5ZM1.625 0.75C1.40951 0.75 1.20285 0.829018 1.05048 0.96967C0.898102 1.11032 0.8125 1.30109 0.8125 1.5L0.8125 10.9245L4.64994 9.063C4.71661 9.02204 4.79491 9.00019 4.875 9.00019C4.95509 9.00019 5.03339 9.02204 5.10006 9.063L8.9375 10.9245L8.9375 1.5C8.9375 1.30109 8.8519 1.11032 8.69952 0.96967C8.54715 0.829018 8.34049 0.75 8.125 0.75L1.625 0.75Z"
          />
        </Vector_0004>
      </BiBookmark>
      <BiBookmark_0001>
        <Vector_0004 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M0 1.5C-1.80411e-16 1.10218 0.171205 0.720644 0.475951 0.43934C0.780698 0.158035 1.19402 4.57967e-16 1.625 8.32667e-17L8.125 0C8.55598 2.08167e-16 8.9693 0.158035 9.27405 0.43934C9.57879 0.720644 9.75 1.10218 9.75 1.5L9.75 11.625C9.74996 11.6928 9.72999 11.7594 9.69222 11.8176C9.65445 11.8758 9.60028 11.9234 9.5355 11.9554C9.47072 11.9874 9.39774 12.0026 9.32434 11.9994C9.25094 11.9961 9.17986 11.9746 9.11869 11.937L4.875 9.82575L0.631312 11.937C0.570136 11.9746 0.499062 11.9961 0.425662 11.9994C0.352261 12.0026 0.279283 11.9874 0.2145 11.9554C0.149716 11.9234 0.0955533 11.8758 0.0577802 11.8176C0.020007 11.7594 3.79603e-05 11.6928 0 11.625L0 1.5ZM1.625 0.75C1.40951 0.75 1.20285 0.829018 1.05048 0.96967C0.898102 1.11032 0.8125 1.30109 0.8125 1.5L0.8125 10.9245L4.64994 9.063C4.71661 9.02204 4.79491 9.00019 4.875 9.00019C4.95509 9.00019 5.03339 9.02204 5.10006 9.063L8.9375 10.9245L8.9375 1.5C8.9375 1.30109 8.8519 1.11032 8.69952 0.96967C8.54715 0.829018 8.34049 0.75 8.125 0.75L1.625 0.75Z"
          />
        </Vector_0004>
      </BiBookmark_0001>
      <BiBookmark_0002>
        <Vector_0004 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M0 1.5C-1.80411e-16 1.10218 0.171205 0.720644 0.475951 0.43934C0.780698 0.158035 1.19402 4.57967e-16 1.625 8.32667e-17L8.125 0C8.55598 2.08167e-16 8.9693 0.158035 9.27405 0.43934C9.57879 0.720644 9.75 1.10218 9.75 1.5L9.75 11.625C9.74996 11.6928 9.72999 11.7594 9.69222 11.8176C9.65445 11.8758 9.60028 11.9234 9.5355 11.9554C9.47072 11.9874 9.39774 12.0026 9.32434 11.9994C9.25094 11.9961 9.17986 11.9746 9.11869 11.937L4.875 9.82575L0.631312 11.937C0.570136 11.9746 0.499062 11.9961 0.425662 11.9994C0.352261 12.0026 0.279283 11.9874 0.2145 11.9554C0.149716 11.9234 0.0955533 11.8758 0.0577802 11.8176C0.020007 11.7594 3.79603e-05 11.6928 0 11.625L0 1.5ZM1.625 0.75C1.40951 0.75 1.20285 0.829018 1.05048 0.96967C0.898102 1.11032 0.8125 1.30109 0.8125 1.5L0.8125 10.9245L4.64994 9.063C4.71661 9.02204 4.79491 9.00019 4.875 9.00019C4.95509 9.00019 5.03339 9.02204 5.10006 9.063L8.9375 10.9245L8.9375 1.5C8.9375 1.30109 8.8519 1.11032 8.69952 0.96967C8.54715 0.829018 8.34049 0.75 8.125 0.75L1.625 0.75Z"
          />
        </Vector_0004>
      </BiBookmark_0002>
      <BiBookmark_0003>
        <Vector_0004 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(153, 153, 153)"
            d="M0 1.5C-1.80411e-16 1.10218 0.171205 0.720644 0.475951 0.43934C0.780698 0.158035 1.19402 4.57967e-16 1.625 8.32667e-17L8.125 0C8.55598 2.08167e-16 8.9693 0.158035 9.27405 0.43934C9.57879 0.720644 9.75 1.10218 9.75 1.5L9.75 11.625C9.74996 11.6928 9.72999 11.7594 9.69222 11.8176C9.65445 11.8758 9.60028 11.9234 9.5355 11.9554C9.47072 11.9874 9.39774 12.0026 9.32434 11.9994C9.25094 11.9961 9.17986 11.9746 9.11869 11.937L4.875 9.82575L0.631312 11.937C0.570136 11.9746 0.499062 11.9961 0.425662 11.9994C0.352261 12.0026 0.279283 11.9874 0.2145 11.9554C0.149716 11.9234 0.0955533 11.8758 0.0577802 11.8176C0.020007 11.7594 3.79603e-05 11.6928 0 11.625L0 1.5ZM1.625 0.75C1.40951 0.75 1.20285 0.829018 1.05048 0.96967C0.898102 1.11032 0.8125 1.30109 0.8125 1.5L0.8125 10.9245L4.64994 9.063C4.71661 9.02204 4.79491 9.00019 4.875 9.00019C4.95509 9.00019 5.03339 9.02204 5.10006 9.063L8.9375 10.9245L8.9375 1.5C8.9375 1.30109 8.8519 1.11032 8.69952 0.96967C8.54715 0.829018 8.34049 0.75 8.125 0.75L1.625 0.75Z"
          />
        </Vector_0004>
      </BiBookmark_0003>
      <_200Upvotes>200 Upvotes</_200Upvotes>
      <_200Upvotes_0001>200 Upvotes</_200Upvotes_0001>
      <_200Upvotes_0002>200 Upvotes</_200Upvotes_0002>
      <_200Upvotes_0003>200 Upvotes</_200Upvotes_0003>
      <Chevron src="/images/chevron.png" alt="image of Chevron" />
      <Chevron_0001 src="/images/chevron.png" alt="image of Chevron" />
      <Chevron_0002 src="/images/chevron.png" alt="image of Chevron" />
      <Vector_0008 src="/images/Vector.png" alt="image of Vector" />
      <Vector_0009 src="/images/Vector.png" alt="image of Vector" />
      <Vector_0010 src="/images/Vector.png" alt="image of Vector" />
      <Vector_0011 src="/images/Vector.png" alt="image of Vector" />
      <Vector_0012 xmlns="http://www.w3.org/2000/svg">
        <path
          fill="black"
          d="M1.5275 0L6.5 5.11123L11.4725 0L13 1.57354L6.5 8.26947L0 1.57354L1.5275 0Z"
        />
      </Vector_0012>
      <Vector_0013 xmlns="http://www.w3.org/2000/svg">
        <path
          fill="rgb(167, 167, 167)"
          d="M13.5792 12.3522L12.721 12.3522L12.4168 12.049C13.4814 10.7689 14.1224 9.10694 14.1224 7.29903C14.1224 3.26772 10.9611 0 7.06118 0C3.16124 0 0 3.26772 0 7.29903C0 11.3303 3.16124 14.5981 7.06118 14.5981C8.81018 14.5981 10.418 13.9355 11.6564 12.8351L11.9497 13.1495L11.9497 14.0366L17.3814 19.64L19 17.9668L13.5792 12.3522L13.5792 12.3522ZM7.06118 12.3522C4.3562 12.3522 2.17267 10.0951 2.17267 7.29903C2.17267 4.50294 4.3562 2.24585 7.06118 2.24585C9.76615 2.24585 11.9497 4.50294 11.9497 7.29903C11.9497 10.0951 9.76615 12.3522 7.06118 12.3522Z"
        />
      </Vector_0013>
      <Categories_0001>Categories</Categories_0001>
      <SortBy>Sort By</SortBy>
     
	 
	  <FundementalsOfWebDev>Fundamentals of Web Dev</FundementalsOfWebDev> 
      <FundementalsOfWebDev_0001>Fundamentals of Web Dev</FundementalsOfWebDev_0001>
      <FundementalsOfWebDev_0002>Fundamentals of Web Dev</FundementalsOfWebDev_0002>
      <FundementalsOfWebDev_0003>Fundamentals of Web Dev</FundementalsOfWebDev_0003>
      <FundementalsOfWebDev_0004>Fundamentals of Web Dev</FundementalsOfWebDev_0004>
      <FundementalsOfWebDev_0005>Fundamentals of Web Dev</FundementalsOfWebDev_0005>
      <FundementalsOfWebDev_0006>Fundamentals of Web Dev</FundementalsOfWebDev_0006>
      


	  <Vector_0014 src="/images/Vector.png" alt="icon" />
      <Vector_0015 src="/images/Vector.png" alt="icon" />
      <Vector_0016 src="/images/Vector.png" alt="icon" />
      <Vector_0017 src="/images/Vector.png" alt="icon" />
      <Vector_0018 src="/images/Vector.png" alt="icon" />
      <Vector_0019 src="/images/Vector.png" alt="icon" />
      <Vector_0020 src="/images/Vector.png" alt="icon" />
      <Vector_0021 src="/images/Vector.png" alt="icon" />
      <Vector_0022 src="/images/Vector.png" alt="icon" />
      <Vector_0023 src="/images/Vector.png" alt="icon" />
      <Vector_0024 src="/images/Vector.png" alt="icon" />
      <Price>Price</Price>
      <DifficultyLevel>Difficulty Level</DifficultyLevel>
      <Free_0004>Free</Free_0004>
      <Beginner_0004>Beginner</Beginner_0004>
      <Paid>Paid</Paid>
      <Intermediate>Intermediate</Intermediate>
      <Advanced>Advanced</Advanced>
      <SeeMore>See More</SeeMore>
      <Vector_0025 src="/images/CheckedVector.png" alt="icon" />
    </RootWrapperExploreResourcesPage>
  );
}

const RootWrapperExploreResourcesPage = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Rectangle26 = styled.div`
	width: 115px;
	height: 48px;
	background-color: white;
	border: solid 1px rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 1038px;
	top: 42px;
`;

const Rectangle27 = styled.div`
	width: 115px;
	height: 48px;
	background-color: rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 1178px;
	top: 42px;
`;

const LogIn = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 93px;
	min-height: 37px;
	position: absolute;
	left: 1050px;
	top: 48px;
	height: 37px;
`;

const SignUp = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 95px;
	min-height: 37px;
	position: absolute;
	left: 1190px;
	top: 48px;
	height: 37px;
`;

const EdisHub = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: "Nova Oval", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 151px;
	min-height: 129px;
	position: absolute;
	left: 219px;
	top: 0px;
	height: 129px;
`;

const Group14 = styled.div`
	width: 102px;
	height: 36px;
	position: absolute;
	left: 392px;
	top: 46px;
`;

const Categories = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 102px;
	min-height: 36px;
	position: absolute;
	left: 0px;
	top: 0px;
	height: 36px;
`;

const Group27 = styled.div`
	width: 472px;
	height: 48px;
	position: absolute;
	left: 530px;
	top: 42px;
`;

const Rectangle16 = styled.div`
	width: 472px;
	height: 48px;
	background-color: white;
	border: solid 1px black;
	border-radius: 50px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const SearchForAnything = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 273px;
	min-height: 38px;
	position: absolute;
	left: 41px;
	top: 5px;
	height: 38px;
`;

const Rectangle15 = styled.div`
	width: 1512px;
	height: 302px;
	background-color: rgba(56, 95, 185, 0.17);
	position: absolute;
	left: 0px;
	top: 128px;
`;

const ExploreDevelopmentResources = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 48px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 745px;
	min-height: 148px;
	position: absolute;
	left: 213px;
	top: 160px;
	height: 148px;
`;

const WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 431px;
	min-height: 36px;
	position: absolute;
	left: 213px;
	top: 323px;
	height: 36px;
`;

const SelectYourLevelOfLearning = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 141px;
	min-height: 36px;
	position: absolute;
	left: 791px;
	top: 323px;
	height: 36px;
`;

const SelectTheAppropriateTopicS = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 173px;
	min-height: 36px;
	position: absolute;
	left: 965px;
	top: 323px;
	height: 36px;
`;

const LearnAtYourOwnPace = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 127px;
	min-height: 36px;
	position: absolute;
	left: 1171px;
	top: 323px;
	height: 36px;
`;

const Learning1 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 1178px;
	top: 190px;
`;

const Settings11 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 812px;
	top: 190px;
`;

const TrendingTopic1 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 1002px;
	top: 190px;
`;

const YourResourcePicks = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 557px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 464px;
	height: 60px;
`;

const _10Results = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 326px;
	min-height: 36px;
	position: absolute;
	left: 470px;
	top: 481px;
	height: 36px;
`;

const Group18 = styled.div`
	width: 412px;
	height: 396px;
	position: absolute;
	left: 537px;
	top: 591px;
`;

const Rectangle24 = styled.div`
	width: 412px;
	height: 396px;
	box-shadow: 5px 6px 16px 2px rgba(0, 0, 0, 0.25);
	background-color: white;
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group32 = styled.div`
	width: 412px;
	height: 396px;
	position: absolute;
	left: 537px;
	top: 1029px;
`;

const Group28 = styled.div`
	width: 412px;
	height: 396px;
	position: absolute;
	left: 1020px;
	top: 591px;
`;

const Group33 = styled.div`
	width: 412px;
	height: 396px;
	position: absolute;
	left: 1020px;
	top: 1029px;
`;

const Rectangle7 = styled.img`
	width: 361px;
	height: 142px;
	object-fit: cover;
	position: absolute;
	left: 562px;
	top: 694px;
`;

const Rectangle29 = styled.img`
	width: 361px;
	height: 142px;
	object-fit: cover;
	position: absolute;
	left: 562px;
	top: 1132px;
`;

const Rectangle28 = styled.img`
	width: 362px;
	height: 142px;
	object-fit: cover;
	position: absolute;
	left: 1044px;
	top: 694px;
`;

const Rectangle30 = styled.img`
	width: 362px;
	height: 142px;
	object-fit: cover;
	position: absolute;
	left: 1044px;
	top: 1132px;
`;

const IntroductionToComputerScience = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 523px;
	min-height: 36px;
	position: absolute;
	left: 562px;
	top: 622px;
	height: 36px;
`;

const IntroductionToComputerScience_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 523px;
	min-height: 36px;
	position: absolute;
	left: 562px;
	top: 1060px;
	height: 36px;
`;

const IntroductionToComputerScience_0002 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 524px;
	min-height: 36px;
	position: absolute;
	left: 1044px;
	top: 622px;
	height: 36px;
`;

const IntroductionToComputerScience_0003 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 524px;
	min-height: 36px;
	position: absolute;
	left: 1044px;
	top: 1060px;
	height: 36px;
`;

const HarvardUniversityCourse60Minutes = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 397px;
	min-height: 35px;
	position: absolute;
	left: 562px;
	top: 843px;
	height: 35px;
`;

const HarvardUniversityCourse60Minutes_0001 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 397px;
	min-height: 35px;
	position: absolute;
	left: 562px;
	top: 1281px;
	height: 35px;
`;

const HarvardUniversityCourse60Minutes_0002 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 397px;
	min-height: 35px;
	position: absolute;
	left: 1044px;
	top: 843px;
	height: 35px;
`;

const HarvardUniversityCourse60Minutes_0003 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 397px;
	min-height: 35px;
	position: absolute;
	left: 1044px;
	top: 1281px;
	height: 35px;
`;

const Group15 = styled.div`
	width: 142px;
	height: 31px;
	position: absolute;
	left: 562px;
	top: 920px;
`;

const Rectangle17 = styled.div`
	width: 142px;
	height: 31px;
	background-color: rgb(56, 95, 185);
	position: absolute;
	left: 0px;
	top: 0px;
`;

const StaffPicked = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 114px;
	min-height: 20px;
	position: absolute;
	left: 14px;
	top: 6px;
	height: 20px;
`;

const Group34 = styled.div`
	width: 142px;
	height: 31px;
	position: absolute;
	left: 562px;
	top: 1358px;
`;

const Group29 = styled.div`
	width: 142px;
	height: 31px;
	position: absolute;
	left: 1044px;
	top: 920px;
`;

const Group35 = styled.div`
	width: 142px;
	height: 31px;
	position: absolute;
	left: 1044px;
	top: 1358px;
`;

const Group16 = styled.div`
	width: 110px;
	height: 31px;
	position: absolute;
	left: 723px;
	top: 920px;
`;

const Rectangle28_0001 = styled.div`
	width: 110px;
	height: 31px;
	background-color: rgb(56, 95, 185);
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Beginner = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 82px;
	min-height: 20px;
	position: absolute;
	left: 14px;
	top: 6px;
	height: 20px;
`;

const Group36 = styled.div`
	width: 110px;
	height: 31px;
	position: absolute;
	left: 723px;
	top: 1358px;
`;

const Group30 = styled.div`
	width: 110px;
	height: 31px;
	position: absolute;
	left: 1206px;
	top: 920px;
`;

const Group37 = styled.div`
	width: 110px;
	height: 31px;
	position: absolute;
	left: 1206px;
	top: 1358px;
`;

const Group17 = styled.div`
	width: 72px;
	height: 31px;
	position: absolute;
	left: 852px;
	top: 920px;
`;

const Rectangle29_0001 = styled.div`
	width: 72px;
	height: 31px;
	background-color: rgb(56, 95, 185);
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Free = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 43px;
	min-height: 20px;
	position: absolute;
	left: 14px;
	top: 6px;
	height: 20px;
`;

const Group38 = styled.div`
	width: 72px;
	height: 31px;
	position: absolute;
	left: 852px;
	top: 1358px;
`;

const Group31 = styled.div`
	width: 72px;
	height: 31px;
	position: absolute;
	left: 1334px;
	top: 920px;
`;

const Group39 = styled.div`
	width: 72px;
	height: 31px;
	position: absolute;
	left: 1334px;
	top: 1358px;
`;

const Bookmark = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 72px;
	min-height: 16px;
	position: absolute;
	left: 852px;
	top: 886px;
	height: 16px;
`;

const Bookmark_0001 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 72px;
	min-height: 16px;
	position: absolute;
	left: 852px;
	top: 1324px;
	height: 16px;
`;

const Bookmark_0002 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 73px;
	min-height: 16px;
	position: absolute;
	left: 1334px;
	top: 886px;
	height: 16px;
`;

const Bookmark_0003 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 73px;
	min-height: 16px;
	position: absolute;
	left: 1334px;
	top: 1324px;
	height: 16px;
`;

const _15Comments = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 120px;
	min-height: 31px;
	position: absolute;
	left: 714px;
	top: 877px;
	height: 31px;
`;

const _15Comments_0001 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 120px;
	min-height: 31px;
	position: absolute;
	left: 714px;
	top: 1315px;
	height: 31px;
`;

const _15Comments_0002 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 120px;
	min-height: 31px;
	position: absolute;
	left: 1197px;
	top: 877px;
	height: 31px;
`;

const _15Comments_0003 = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 120px;
	min-height: 31px;
	position: absolute;
	left: 1197px;
	top: 1315px;
	height: 31px;
`;

const FaRegularCommentAlt = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 697px;
	top: 888px;
`;

const Vector = styled.svg`
	width: 13px;
	height: 12px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const FaRegularCommentAlt_0001 = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 697px;
	top: 1326px;
`;

const FaRegularCommentAlt_0002 = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 1180px;
	top: 888px;
`;

const FaRegularCommentAlt_0003 = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 1180px;
	top: 1326px;
`;

const BiBookmark = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 837px;
	top: 888px;
`;

const Vector_0004 = styled.svg`
	width: 10px;
	height: 12px;
	position: absolute;
	left: 2px;
	top: 0px;
	right: 2px;
	bottom: 0px;
`;

const BiBookmark_0001 = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 837px;
	top: 1326px;
`;

const BiBookmark_0002 = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 1319px;
	top: 888px;
`;

const BiBookmark_0003 = styled.div`
	width: 13px;
	height: 12px;
	overflow: hidden;
	position: absolute;
	left: 1319px;
	top: 1326px;
`;

const _200Upvotes = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 112px;
	min-height: 16px;
	position: absolute;
	left: 576px;
	top: 884px;
	height: 16px;
`;

const _200Upvotes_0001 = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 112px;
	min-height: 16px;
	position: absolute;
	left: 576px;
	top: 1322px;
	height: 16px;
`;

const _200Upvotes_0002 = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 113px;
	min-height: 16px;
	position: absolute;
	left: 1058px;
	top: 884px;
	height: 16px;
`;

const _200Upvotes_0003 = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 113px;
	min-height: 16px;
	position: absolute;
	left: 1058px;
	top: 1322px;
	height: 16px;
`;

const Chevron = styled.img`
	width: 14px;
	height: 14px;
	object-fit: cover;
	position: absolute;
	left: 558px;
	top: 885px;
`;

const Chevron_0001 = styled.img`
	width: 16px;
	height: 14px;
	object-fit: cover;
	position: absolute;
	left: 1042px;
	top: 885px;
`;

const Chevron_0002 = styled.img`
	width: 16px;
	height: 14px;
	object-fit: cover;
	position: absolute;
	left: 1042px;
	top: 1323px;
`;

const Vector_0008 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 564px;
	top: 814px;
	right: 844px;
	bottom: 567px;
`;

const Vector_0009 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 564px;
	top: 1252px;
	right: 844px;
	bottom: 129px;
`;

const Vector_0010 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 1047px;
	top: 814px;
	right: 362px;
	bottom: 567px;
`;

const Vector_0011 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 1047px;
	top: 1252px;
	right: 362px;
	bottom: 129px;
`;

const Vector_0012 = styled.svg`
	width: 13px;
	height: 8px;
	position: absolute;
	left: 494px;
	top: 64px;
	right: 1005px;
	bottom: 1405px;
`;

const Vector_0013 = styled.svg`
	width: 19px;
	height: 20px;
	position: absolute;
	left: 547px;
	top: 59px;
	right: 946px;
	bottom: 1398px;
`;

const Categories_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 286px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 770px;
	height: 60px;
`;

const SortBy = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 290px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 539px;
	height: 60px;
`;

const FundementalsOfWebDev = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 835px;
	height: 29px;
`;

const FundementalsOfWebDev_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 976px;
	height: 29px;
`;

const FundementalsOfWebDev_0002 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 882px;
	height: 29px;
`;

const FundementalsOfWebDev_0003 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 1023px;
	height: 29px;
`;

const FundementalsOfWebDev_0004 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 930px;
	height: 29px;
`;

const FundementalsOfWebDev_0005 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 1116px;
	height: 29px;
`;

const FundementalsOfWebDev_0006 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 1071px;
	height: 29px;
`;

const Vector_0014 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 958px;
	right: 1345px;
	bottom: 491px;
`;

const Vector_0015 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 864px;
	right: 1345px;
	bottom: 585px;
`;

const Vector_0016 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 911px;
	right: 1345px;
	bottom: 538px;
`;

const Vector_0017 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 693px;
	right: 1345px;
	bottom: 756px;
`;

const Vector_0018 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 740px;
	right: 1345px;
	bottom: 709px;
`;

const Vector_0019 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 1362px;
	right: 1345px;
	bottom: 87px;
`;

const Vector_0020 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 1410px;
	right: 1345px;
	bottom: 39px;
`;

const Vector_0021 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 1005px;
	right: 1345px;
	bottom: 444px;
`;

const Vector_0022 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 1099px;
	right: 1345px;
	bottom: 350px;
`;

const Vector_0023 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 1052px;
	right: 1345px;
	bottom: 397px;
`;

const Vector_0024 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 139px;
	top: 1146px;
	right: 1345px;
	bottom: 303px;
`;

const Price = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 286px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 599px;
	height: 60px;
`;

const DifficultyLevel = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 290px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 1221px;
	height: 60px;
`;

const Free_0004 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 286px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 664px;
	height: 29px;
`;

const Beginner_0004 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 286px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 1286px;
	height: 29px;
`;

const Paid = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 286px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 711px;
	height: 29px;
`;

const Intermediate = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 286px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 1333px;
	height: 29px;
`;

const Advanced = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 286px;
	min-height: 29px;
	position: absolute;
	left: 180px;
	top: 1381px;
	height: 29px;
`;

const SeeMore = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	text-decoration: underline;
	width: 290px;
	min-height: 29px;
	position: absolute;
	left: 139px;
	top: 1162px;
	height: 29px;
`;

const Vector_0025 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 140px;
	top: 1287px;
	right: 1344px;
	bottom: 162px;
`;