// import React from "react";
import styled from "styled-components";
/**
 * `<ExploreResourcesPage>` ('EXPLORE RESOURCES PAGE')
 * - [Open in Figma](https://figma.com/file/ccmRe7vzcfeTsD78jd0hHR?node-id=149:2150)
 * - [Open in Grida](https://code.grida.co/files/ccmRe7vzcfeTsD78jd0hHR?node=149:2150)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <ExploreResourcesPage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/54d97f80-e5a4-483a-bf0a-a0b2ef14b996)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://ccmRe7vzcfeTsD78jd0hHR/149:2150 -->
 */

import Link from "next/link";

export default function ExploreResourcesPage() {
	return (
		<RootWrapperExploreResourcesPage>
			<Rectangle15>
				<ExploreDevelopmentResources>
					Explore Development
					<br />
					Resources
				</ExploreDevelopmentResources>
				<WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds>
					Whether you’re a full-time student, bootcamp graduate, or working professional, we’ve got
					resources curated for your needs.
				</WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds>
				<SelectYourLevelOfLearning>Select your level of learning</SelectYourLevelOfLearning>
				<SelectTheAppropriateTopicS>Select the appropriate topic(s)</SelectTheAppropriateTopicS>
				<LearnAtYourOwnPace>Learn at your own pace</LearnAtYourOwnPace>
				<Learning1
					src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a6857f51-ba1e-4a83-ac40-0e506b83c963"
					alt="image of Learning1"
				/>
				<Settings11
					src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ec9275e0-8b7b-46dc-ac1d-588a602e3f40"
					alt="image of Settings11"
				/>
				<TrendingTopic1
					src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/68ffe05f-77df-46c2-adc7-b41ecbde05d7"
					alt="image of TrendingTopic1"
				/>
			</Rectangle15>
			<SelectYourLevelOfLearning_0001>Select Your Level of Learning</SelectYourLevelOfLearning_0001>
			<Group39>
				<Rectangle24 />
			</Group39>
			<Group40>
				<Rectangle24 />
			</Group40>
			<Group41>
				<Rectangle24 />
			</Group41>
			<Beginner>Beginner</Beginner>
			<Intermediate>Intermediate</Intermediate>
			<Advanced>Advanced</Advanced>
			<MaySelectOnlyOne>(may select only one)</MaySelectOnlyOne>
			<Rectangle44 />
			<Continue    >
				<Link href="/ResourceCartegories" >
					<a style={{
						color: "white",
						textDecoration: "none",
					}}>
						Continue
					</a>
				</Link>
			</Continue>
			<OrViewAllDevelopmentResources>
				or view all development resources
			</OrViewAllDevelopmentResources>
		</RootWrapperExploreResourcesPage>
	);
}

const RootWrapperExploreResourcesPage = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Rectangle26 = styled.div`
	width: 115px;
	height: 48px;
	background-color: white;
	border: solid 1px rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 1038px;
	top: 42px;
`;

const Rectangle27 = styled.div`
	width: 115px;
	height: 48px;
	background-color: rgb(56, 95, 185);
	border-radius: 10px;
	position: absolute;
	left: 1178px;
	top: 42px;
`;

const LogIn = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 113px;
	min-height: 37px;
	position: absolute;
	left: 1050px;
	top: 48px;
	height: 37px;
`;

const SignUp = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 135px;
	min-height: 37px;
	position: absolute;
	left: 1190px;
	top: 48px;
	height: 37px;
`;

const EdisHub = styled.span`
	color: rgb(56, 95, 185);
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: "Nova Oval", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 151px;
	min-height: 129px;
	position: absolute;
	left: 219px;
	top: 0px;
	height: 129px;
`;

const Group14 = styled.div`
	width: 102px;
	height: 36px;
	position: absolute;
	left: 392px;
	top: 46px;
`;

const Categories = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 102px;
	min-height: 36px;
	position: absolute;
	left: 0px;
	top: 0px;
	height: 36px;
`;

const Group27 = styled.div`
	width: 472px;
	height: 48px;
	position: absolute;
	left: 530px;
	top: 42px;
`;

const Rectangle16 = styled.div`
	width: 472px;
	height: 48px;
	background-color: white;
	border: solid 1px black;
	border-radius: 50px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const SearchForAnything = styled.span`
	color: rgb(167, 167, 167);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 313px;
	min-height: 38px;
	position: absolute;
	left: 41px;
	top: 5px;
	height: 38px;
`;

const Rectangle15 = styled.div`
	width: 1512px;
	height: 302px;
	background-color: rgba(56, 95, 185, 0.17);
	position: absolute;
	left: 0px;
	top: -1px;
`;

const ExploreDevelopmentResources = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 48px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 787px;
	min-height: 148px;
	position: absolute;
	left: 213px;
	top: 45px;
	height: 148px;
`;

const WhetherYouReAFullTimeStudentBootcampGraduateOrWorkingProfessionalWeVeGotResourcesCuratedForYourNeeds = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: left;
	width: 431px;
	min-height: 36px;
	position: absolute;
	left: 213px;
	top: 185px;
	height: 36px;
`;

const SelectYourLevelOfLearning = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 141px;
	min-height: 36px;
	position: absolute;
	left: 791px;
	top: 235px;
	height: 36px;
`;

const SelectTheAppropriateTopicS = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 173px;
	min-height: 36px;
	position: absolute;
	left: 965px;
	top: 235px;
	height: 36px;
`;

const LearnAtYourOwnPace = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 167px;
	min-height: 36px;
	position: absolute;
	left: 1171px;
	top: 235px;
	height: 36px;
`;

const Learning1 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 1178px;
	top: 120px;
`;

const Settings11 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 812px;
	top: 120px;
`;

const TrendingTopic1 = styled.img`
	width: 100px;
	height: 100px;
	object-fit: cover;
	position: absolute;
	left: 1002px;
	top: 120px;
`;

const SelectYourLevelOfLearning_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 599px;
	min-height: 60px;
	position: absolute;
	left: 139px;
	top: 520px;
	height: 60px;
`;

const Group39 = styled.div`
	width: 240px;
	height: 112px;
	position: absolute;
	left: 345px;
	top: 644px;
`;

const Rectangle24 = styled.div`
	width: 240px;
	height: 112px;
	box-shadow: 0px 2px 9px -2px rgb(56, 95, 185);
	background-color: white;
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group40 = styled.div`
	width: 240px;
	height: 112px;
	position: absolute;
	left: 636px;
	top: 644px;
`;

const Group41 = styled.div`
	width: 240px;
	height: 112px;
	position: absolute;
	left: 927px;
	top: 644px;
`;

const Beginner = styled.span`
	color: Black;
	background-color: blue-btn ;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 270px;
	min-height: 36px;
	position: absolute;
	left: 330px;
	top: 682px;
	height: 36px;
`;

const Intermediate = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 270px;
	min-height: 36px;
	position: absolute;
	left: 621px;
	top: 682px;
	height: 36px;
`;

const Advanced = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 270px;
	min-height: 36px;
	position: absolute;
	left: 912px;
	top: 682px;
	height: 36px;
`;

const MaySelectOnlyOne = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 314px;
	min-height: 36px;
	position: absolute;
	left: 139px;
	top: 572px;
	height: 36px;
`;

const Rectangle44 = styled.div`
	width: 500px;
	height: 65px;
	background-color: rgba(56, 95, 185, 0.5);
	border-radius: 10px;
	position: absolute;
	left: 506px;
	top: 805px;
`;

const Continue = styled.span`
	color: rgba(255, 255, 255, 0.5);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	text-align: center;
	width: 270px;
	min-height: 36px;
	position: absolute;
	left: 621px;
	top: 820px;
	height: 36px;
`;

const OrViewAllDevelopmentResources = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: center;
	width: 276px;
	min-height: 36px;
	position: absolute;
	left: 618px;
	top: 882px;
	height: 36px;
`;

const Vector = styled.svg`
	width: 13px;
	height: 8px;
	position: absolute;
	left: 494px;
	top: 64px;
	right: 1005px;
	bottom: 910px;
`;

const Vector_0001 = styled.svg`
	width: 19px;
	height: 20px;
	position: absolute;
	left: 547px;
	top: 59px;
	right: 946px;
	bottom: 903px;
`;